### ISSUE TITLE
All possible first level errors ?

### ISSUE THREAD

**Issue by ashishpawar517** [ashishpawar517/AutoCompiler#13]
Please report all possible simple errors that we can put as milestone for AutoCompiler. 
1. Semicolon missing
2. bracket errors
3. arrays [] 

Please discuss them here !

**Comment by pawarashish564** [comment]
When a curly brace is missing the compiler error is 
> # reached end of file while parsing

**Comment by pawarashish564** [comment]
new commit with new methods and new error handling 
```java
RandomWriter commentLine()// for comment specific line in file
```

**Comment by pawarashish564** [comment]
Currently working on public class name and not matching with file name.

**Comment by pawarashish564** [comment]
https://github.com/pawarashish564/AutoCompiler/commit/4a0cdb6318d22ff14a7e974b71a9331d36d22f3f

**Comment by Chandni-bhatia** [comment]
package system does not exist !

**Comment by pawarashish564** [comment]
??
